/* Original Story Time books. One character, one problem, one ending.
   Topic maintenance: extra detail stays ON this story. Not copyrighted test items.
   中文 is parent-to-toddler talk (Bellevue Mandarin, ~3.5). English unused in Story Time.
   Off-topic foils are other-story pictures — never cars/trucks/garage.
   Parent script: join what he said, then ask back to THIS story. Do not park with 「车待会再讲」. */
const STORY_BOOKS = [
  {
    id: "hat",
    titleEn: "The Yellow Hat",
    titleZh: "小黄帽",
    topicEn: "the yellow hat",
    topicZh: "小黄帽",
    parentStayEn: "Catch what he said, then ask back to the hat.",
    parentStayZh: "先接住他的话，再问回帽子。他说恐龙：恐龙呀。那恐龙想戴小黄帽吗？帽子在哪里？",
    parentCarZh: "车也来了。那小车要帮小明找帽子吗？帽子在哪里？",
    belongFoil: {
      book: "duck",
      file: "p1",
      bridgeZh: "小鸭子也来找帽子了吗？帽子在哪里？",
    },
    pages: [
      {
        id: "p1",
        en: "This is Min. He loves his yellow hat. Soft. Warm. Just right. “My hat,” says Min.",
        zh: "诶，小明出门了，头上戴着他的黄帽子。他还摸着帽子呢。好看吧？",
      },
      {
        id: "p2",
        en: "Whoosh! A big wind comes. The yellow hat flies up, up, up. “Oh no! My hat!” Min reaches high.",
        zh: "呼——风一吹，帽子飞走啦！哎呀，抓也抓不到。帽子呢？",
      },
      {
        id: "p3",
        en: "Min looks and looks, because the hat is gone. Yellow hat, yellow hat… there! In the tree.",
        zh: "小明找啊找。啊，飞到树那边去了！你看见黄帽子了吗？",
      },
      {
        id: "p4",
        en: "Min holds the yellow hat. He puts it back on. Soft again. Warm again. “Hooray! My hat.”",
        zh: "拿到啦！小明把黄帽子戴回去。嘿嘿，又在头上了。",
      },
    ],
    seq: ["p1", "p2", "p4"],
    belongOn: ["p1", "p2", "p4"],
    questions: [
      {
        skill: "detail",
        promptEn: "Min’s hat is soft and warm. Who wears the yellow hat?",
        promptZh: "谁头上戴着那顶黄帽子呀？",
        correct: { book: "hat", file: "p1" },
        foils: [
          { book: "hat", file: "p2", bridgeZh: "这张也有帽子。帽子飞走啦。那谁头上还戴着黄帽子呀？" },
          { book: "hat", file: "p3", bridgeZh: "这张也有帽子。帽子在树上。那谁头上戴着黄帽子呀？" },
          { book: "hat", file: "p4", bridgeZh: "这张也有帽子。戴回去啦。那出门的时候，谁头上戴着黄帽子呀？" },
        ],
      },
      {
        skill: "sequence",
        promptEn: "The wind went whoosh. What happened first?",
        promptZh: "帽子还在头上、还没被风吹走，是哪一张？",
        correct: { book: "hat", file: "p1" },
        foils: [
          { book: "hat", file: "p2", bridgeZh: "这张也是帽子的故事。风已经吹走了。那还在头上的是哪一张？" },
          { book: "hat", file: "p3", bridgeZh: "这张也是帽子的故事。已经飞到树上了。那还在头上的是哪一张？" },
          { book: "hat", file: "p4", bridgeZh: "这张也是帽子的故事。已经戴回去了。那还没被风吹走，是哪一张？" },
        ],
      },
      {
        skill: "topic",
        joinPractice: true,
        promptEn: "Which picture is still our hat story?",
        promptZh: "哪张还是这个故事？",
        correct: { book: "hat", file: "topic" },
        foils: [
          { book: "duck", file: "topic", bridgeZh: "小鸭子也来找帽子了吗？帽子在哪里？" },
          { book: "noodles", file: "topic", bridgeZh: "面条也香。那小明吃面的时候帽子戴着吗？帽子在哪里？" },
          { book: "teddy", file: "topic", bridgeZh: "小熊也来了。那小熊想戴小黄帽吗？帽子在哪里？" },
        ],
      },
    ],
  },
  {
    id: "rain",
    titleEn: "Rain Rain",
    titleZh: "下雨了",
    topicEn: "the rain",
    topicZh: "下雨",
    parentStayEn: "Catch what he said, then ask back to the rain.",
    parentStayZh: "先接住他的话，再问回下雨。他说恐龙：恐龙呀。那恐龙要不要撑伞呀？伞呢？",
    parentCarZh: "车也来了。那小车要不要打伞呀？伞呢？撑开了没有？",
    belongFoil: {
      book: "duck",
      file: "p1",
      bridgeZh: "小鸭子也来淋雨了吗？伞呢？撑开了没有？",
    },
    pages: [
      {
        id: "p1",
        en: "Bo looks up. The sky is gray and quiet. “I think rain is coming,” he says. He holds his yellow umbrella.",
        zh: "诶，天怎么灰灰的。小波抬头看，雨要来了吧？黄伞还拿在手里呢。",
      },
      {
        id: "p2",
        en: "Pitter-patter, pitter-patter. Rain, rain, rain. Cool drops kiss Bo’s raincoat. The sidewalk shines.",
        zh: "啪嗒啪嗒，下雨啦！雨衣都湿湿的。地面亮亮的，看见了吗？",
      },
      {
        id: "p3",
        en: "Bo pops the umbrella open, because the rain is coming down. “Stay dry,” he laughs. Drip, drip, drip on the yellow top.",
        zh: "雨越下越大。小波把黄伞撑开。这下不会淋湿了吧？",
      },
      {
        id: "p4",
        en: "A puddle! Bo jumps. Splash! Water flies. “Again!” he shouts. Rain, rain, rain — and a happy splash.",
        zh: "水坑！小波跳进去，哗啦——水花飞起来。还要再跳一次吗？",
      },
    ],
    seq: ["p1", "p2", "p4"],
    belongOn: ["p2", "p3", "p4"],
    questions: [
      {
        skill: "detail",
        promptEn: "Bo wants to stay dry. What does he open in the rain?",
        promptZh: "下雨了，小波把什么撑开了？",
        correct: { book: "rain", file: "p3" },
        foils: [
          { book: "rain", file: "p1", bridgeZh: "这张也是下雨。伞还拿在手里。那哪一张是撑开了？" },
          { book: "rain", file: "p2", bridgeZh: "这张也是下雨。雨衣湿湿的。那黄伞撑开是哪一张？" },
          { book: "rain", file: "p4", bridgeZh: "这张也是下雨。在跳水坑。那把伞撑开是哪一张？" },
        ],
      },
      {
        skill: "sequence",
        promptEn: "Splash in the puddle. What happened last?",
        promptZh: "跳进水坑、水花飞起来，是哪一张？",
        correct: { book: "rain", file: "p4" },
        foils: [
          { book: "rain", file: "p1", bridgeZh: "这张也是下雨。雨还没下。那跳进水坑是哪一张？" },
          { book: "rain", file: "p2", bridgeZh: "这张也是下雨。刚开始下。那跳进水坑是哪一张？" },
          { book: "rain", file: "p3", bridgeZh: "这张也是下雨。刚撑开伞。那跳进水坑是哪一张？" },
        ],
      },
      {
        skill: "topic",
        joinPractice: true,
        promptEn: "Which picture is still our rain story?",
        promptZh: "哪张还是这个故事？",
        correct: { book: "rain", file: "topic" },
        foils: [
          { book: "teddy", file: "topic", bridgeZh: "小熊也来了。那小熊要不要打伞呀？伞呢？" },
          { book: "noodles", file: "topic", bridgeZh: "面条也香。下雨天吃面吗？伞呢？撑开了没有？" },
          { book: "hat", file: "topic", bridgeZh: "帽子也来了。下雨天帽子会湿吗？伞呢？" },
        ],
      },
    ],
  },
  {
    id: "duck",
    titleEn: "Little Duck Helps",
    titleZh: "小鸭子帮忙",
    topicEn: "the little duck",
    topicZh: "小鸭子",
    parentStayEn: "Catch what he said, then ask back to the duck.",
    parentStayZh: "先接住他的话，再问回小鸭子。他说恐龙：恐龙呀。那恐龙也来帮忙了吗？小鸭子在干嘛呢？",
    parentCarZh: "车也来了。那小车要帮小鸭子送树枝吗？小鸭子在干嘛呢？",
    belongFoil: {
      book: "hat",
      file: "p1",
      bridgeZh: "小黄帽也来帮忙了吗？小鸭子在干嘛呢？",
    },
    pages: [
      {
        id: "p1",
        en: "Little Duck waddles in the grass. Soft grass, tickle-tickle. “A stick!” she peeps. A brown stick, just the right size.",
        zh: "诶，草里面有只小鸭子。它看见一根小树枝。要捡起来吗？",
      },
      {
        id: "p2",
        en: "Oh. The nest in the tree is broken. Sticks falling. Little Duck feels worried. “The nest needs help.”",
        zh: "你看树上，鸟窝的树枝在掉。小鸭子着急了。鸟窝怎么办呀？",
      },
      {
        id: "p3",
        en: "Little Duck picks up the stick, because the nest is broken. She carries it. Waddle, waddle, to the tree.",
        zh: "小鸭子衔起树枝啦。摇摇走，送到树那边去。它在帮忙呢。",
      },
      {
        id: "p4",
        en: "The nest is whole again. Safe. A little bird sings thank you. Little Duck feels proud. “I can help.”",
        zh: "鸟窝好了。小鸟送花说谢谢。小鸭子帮上忙了吧？",
      },
    ],
    seq: ["p1", "p3", "p4"],
    belongOn: ["p1", "p3", "p4"],
    questions: [
      {
        skill: "detail",
        promptEn: "The nest was broken. Who brings the stick to help?",
        promptZh: "谁衔着树枝去帮忙呀？",
        correct: { book: "duck", file: "p3" },
        foils: [
          { book: "duck", file: "p1", bridgeZh: "这张也是小鸭子。还在草里看。那谁衔着树枝去帮忙呀？" },
          { book: "duck", file: "p2", bridgeZh: "这张也是小鸭子。鸟窝坏了。那谁衔着树枝去帮忙呀？" },
          { book: "duck", file: "p4", bridgeZh: "这张也是小鸭子。已经帮完了。那衔着树枝去帮忙，是哪一张？" },
        ],
      },
      {
        skill: "sequence",
        promptEn: "The little bird says thank you. What happened last?",
        promptZh: "小鸟送花说谢谢，是哪一张？",
        correct: { book: "duck", file: "p4" },
        foils: [
          { book: "duck", file: "p1", bridgeZh: "这张也是小鸭子。还刚看见树枝。那小鸟送花说谢谢，是哪一张？" },
          { book: "duck", file: "p2", bridgeZh: "这张也是小鸭子。鸟窝还坏着。那小鸟送花说谢谢，是哪一张？" },
          { book: "duck", file: "p3", bridgeZh: "这张也是小鸭子。正在送树枝。那小鸟送花说谢谢，是哪一张？" },
        ],
      },
      {
        skill: "topic",
        joinPractice: true,
        promptEn: "Which picture is still our duck story?",
        promptZh: "哪张还是这个故事？",
        correct: { book: "duck", file: "topic" },
        foils: [
          { book: "swing", file: "topic", bridgeZh: "秋千也来了。小鸭子想荡秋千吗？小鸭子在干嘛呢？" },
          { book: "noodles", file: "topic", bridgeZh: "面条也香。小鸭子也来吃面了吗？小鸭子在干嘛呢？" },
          { book: "hat", file: "topic", bridgeZh: "小黄帽也来帮忙了吗？小鸭子在干嘛呢？" },
        ],
      },
    ],
  },
  {
    id: "swing",
    titleEn: "The Red Swing",
    titleZh: "红色秋千",
    topicEn: "the red swing",
    topicZh: "红色秋千",
    parentStayEn: "Catch what he said, then ask back to the swing.",
    parentStayZh: "先接住他的话，再问回秋千。他说恐龙：恐龙呀。那恐龙想荡秋千吗？谁在秋千上呀？",
    parentCarZh: "车也来了。那小车想荡秋千吗？谁在秋千上呀？",
    belongFoil: {
      book: "ball",
      file: "p1",
      bridgeZh: "皮球也想荡秋千吗？谁在秋千上呀？",
    },
    pages: [
      {
        id: "p1",
        en: "Mei is at the park. She sees a red swing. Empty. Waiting. “That swing looks fun,” she says.",
        zh: "公园里有个红色秋千。空空的，没人坐。小美要去玩吗？",
      },
      {
        id: "p2",
        en: "Mei sits on the red swing. The seat is smooth. She holds the ropes. “Ready,” she whispers.",
        zh: "坐上去啦。小美抓好链子。准备好了没？",
      },
      {
        id: "p3",
        en: "Swing, swing, swing. Mei goes high. Wind in her hair. Her tummy feels fizzy. “Whee!”",
        zh: "荡起来喽！小美荡得好高。耶——好玩吧？",
      },
      {
        id: "p4",
        en: "Mei’s feet find the ground. She hops down. “All done, red swing.” She feels happy and a little wobbly.",
        zh: "停下来了。小美跳下来，跟秋千拜拜。玩好了吧？",
      },
    ],
    seq: ["p1", "p2", "p4"],
    belongOn: ["p2", "p3", "p4"],
    questions: [
      {
        skill: "detail",
        promptEn: "Mei is at the park. Where is the red swing?",
        promptZh: "红色秋千还空着的时候，小美在哪一张？",
        correct: { book: "swing", file: "p1" },
        foils: [
          { book: "swing", file: "p2", bridgeZh: "这张也是秋千。已经坐上去了。那还空着的是哪一张？" },
          { book: "swing", file: "p3", bridgeZh: "这张也是秋千。已经荡起来了。那还空着的是哪一张？" },
          { book: "swing", file: "p4", bridgeZh: "这张也是秋千。已经跳下来了。那还空着的是哪一张？" },
        ],
      },
      {
        skill: "sequence",
        promptEn: "The swing was empty, waiting. What happened first?",
        promptZh: "秋千还空着、她还没坐上去，是哪一张？",
        correct: { book: "swing", file: "p1" },
        foils: [
          { book: "swing", file: "p2", bridgeZh: "这张也是秋千。已经坐好了。那还空着、还没坐上去，是哪一张？" },
          { book: "swing", file: "p3", bridgeZh: "这张也是秋千。已经荡高了。那还空着、还没坐上去，是哪一张？" },
          { book: "swing", file: "p4", bridgeZh: "这张也是秋千。已经玩好了。那还空着、还没坐上去，是哪一张？" },
        ],
      },
      {
        skill: "topic",
        joinPractice: true,
        promptEn: "Which picture is still our swing story?",
        promptZh: "哪张还是这个故事？",
        correct: { book: "swing", file: "topic" },
        foils: [
          { book: "hat", file: "topic", bridgeZh: "帽子也来了。戴着帽子荡秋千吗？谁在秋千上呀？" },
          { book: "ball", file: "topic", bridgeZh: "皮球也想荡秋千吗？谁在秋千上呀？" },
          { book: "noodles", file: "topic", bridgeZh: "面条也香。吃完面再荡秋千？谁在秋千上呀？" },
        ],
      },
    ],
  },
  {
    id: "ball",
    titleEn: "The Red Ball",
    titleZh: "红皮球",
    topicEn: "the red ball",
    topicZh: "红皮球",
    parentStayEn: "Catch what he said, then ask back to the ball.",
    parentStayZh: "先接住他的话，再问回皮球。他说恐龙：恐龙呀。那恐龙想玩红皮球吗？谁在玩那个红皮球？",
    parentCarZh: "车也来了。那小车想玩红皮球吗？谁在玩那个红皮球？",
    belongFoil: {
      book: "teddy",
      file: "p2",
      bridgeZh: "小熊也来玩皮球了吗？谁在玩那个红皮球？",
    },
    pages: [
      {
        id: "p1",
        en: "Jun has a red ball. Bouncy. Shiny. He holds it tight. The playground feels a little quiet.",
        zh: "小军抱着红皮球。就他自己，有点安静。球是他的吗？",
      },
      {
        id: "p2",
        en: "A friend comes. Lili waves. “Hi! Can I play?” Jun looks at the red ball. He is not sure yet.",
        zh: "丽丽来了，跟他招手。想一起玩红皮球。小军还在想呢。",
      },
      {
        id: "p3",
        en: "They share the red ball. Roll. Catch. Giggle. “Your turn!” “Your turn!” The ball is happier with two.",
        zh: "好，一起玩！两个人抱着红皮球。轮流玩，对不对？",
      },
      {
        id: "p4",
        en: "Jun and Lili sit in the grass. The red ball rests between them. They smile. “We are friends,” says Lili.",
        zh: "坐下来了。红皮球放中间。他们是朋友了吧？",
      },
    ],
    seq: ["p1", "p2", "p4"],
    belongOn: ["p1", "p3", "p4"],
    questions: [
      {
        skill: "detail",
        promptEn: "They take turns. What do the friends share?",
        promptZh: "两个人一起抱着的是什么？",
        correct: { book: "ball", file: "p3" },
        foils: [
          { book: "ball", file: "p1", bridgeZh: "这张也有红皮球。就他自己抱着。那两个人一起抱着，是哪一张？" },
          { book: "ball", file: "p2", bridgeZh: "这张也有红皮球。丽丽刚来。那两个人一起抱着，是哪一张？" },
          { book: "ball", file: "p4", bridgeZh: "这张也有红皮球。已经放中间了。那两个人一起抱着，是哪一张？" },
        ],
      },
      {
        skill: "inference",
        promptEn: "Lili says, “We are friends.” How do they feel at the end?",
        promptZh: "他们笑成这样，是朋友了吧？哪一张？",
        correct: { book: "ball", file: "p4" },
        foils: [
          { book: "ball", file: "p1", bridgeZh: "这张也是皮球。还就他自己。那笑成朋友了，是哪一张？" },
          { book: "ball", file: "p2", bridgeZh: "这张也是皮球。丽丽刚来。那笑成朋友了，是哪一张？" },
          { book: "ball", file: "p3", bridgeZh: "这张也是皮球。正在一起玩。那坐下来笑成朋友，是哪一张？" },
        ],
      },
      {
        skill: "topic",
        joinPractice: true,
        promptEn: "Which picture is still our ball story?",
        promptZh: "哪张还是这个故事？",
        correct: { book: "ball", file: "topic" },
        foils: [
          { book: "duck", file: "topic", bridgeZh: "小鸭子也来玩皮球了吗？谁在玩那个红皮球？" },
          { book: "help", file: "topic", bridgeZh: "帮忙也很好。袋子里有红皮球吗？谁在玩那个红皮球？" },
          { book: "teddy", file: "topic", bridgeZh: "小熊也来玩皮球了吗？谁在玩那个红皮球？" },
        ],
      },
    ],
  },
  {
    id: "teddy",
    titleEn: "Night Night Teddy",
    titleZh: "晚安小熊",
    topicEn: "teddy",
    topicZh: "小熊",
    parentStayEn: "Catch what he said, then ask back to teddy.",
    parentStayZh: "先接住他的话，再问回小熊。他说恐龙：恐龙呀。那恐龙也困了吗？小熊在哪儿呢？",
    parentCarZh: "车也来了。那小车也来睡觉了吗？小熊在哪儿呢？",
    belongFoil: {
      book: "duck",
      file: "p1",
      bridgeZh: "小鸭子也来睡觉了吗？小熊在哪儿呢？",
    },
    pages: [
      {
        id: "p1",
        en: "The moon is round and yellow. Hao holds teddy by the window. “Look, teddy. Night is here.” The room is quiet.",
        zh: "天黑啦。小豪抱着小熊看窗外。月亮出来了，看见没？",
      },
      {
        id: "p2",
        en: "Hao hugs teddy close. Teddy is warm and a little fuzzy. Hao’s shoulders drop. “I like you, teddy.”",
        zh: "再抱紧一点。小熊毛茸茸的。喜欢小熊吗？",
      },
      {
        id: "p3",
        en: "They climb into bed, because it is sleepy time. Quilt up. Teddy under Hao’s chin. “Stay with me.”",
        zh: "该睡觉喽。爬上床，被子盖上。小熊陪着，好不好？",
      },
      {
        id: "p4",
        en: "Eyes closed. Slow breaths. “Night-night, teddy.” Teddy is still warm. The moon watches. All quiet.",
        zh: "眼睛闭上。晚安小熊。睡着了吧？",
      },
    ],
    seq: ["p1", "p2", "p4"],
    belongOn: ["p2", "p3", "p4"],
    questions: [
      {
        skill: "detail",
        promptEn: "Teddy is warm and fuzzy. Who does Hao hug at bedtime?",
        promptZh: "睡觉前小豪抱着谁呀？",
        correct: { book: "teddy", file: "p2" },
        foils: [
          { book: "teddy", file: "p1", bridgeZh: "这张也有小熊。在看月亮。那睡觉前抱紧小熊，是哪一张？" },
          { book: "teddy", file: "p3", bridgeZh: "这张也有小熊。已经上床了。那睡觉前抱着谁呀？" },
          { book: "teddy", file: "p4", bridgeZh: "这张也有小熊。已经睡着了。那睡觉前抱着谁呀？" },
        ],
      },
      {
        skill: "sequence",
        promptEn: "Hao says night-night. What happened last?",
        promptZh: "说了晚安、睡着了，是哪一张？",
        correct: { book: "teddy", file: "p4" },
        foils: [
          { book: "teddy", file: "p1", bridgeZh: "这张也是小熊。还在看月亮。那说了晚安、睡着了，是哪一张？" },
          { book: "teddy", file: "p2", bridgeZh: "这张也是小熊。还在抱。那说了晚安、睡着了，是哪一张？" },
          { book: "teddy", file: "p3", bridgeZh: "这张也是小熊。刚上床。那说了晚安、睡着了，是哪一张？" },
        ],
      },
      {
        skill: "topic",
        joinPractice: true,
        promptEn: "Which picture is still our teddy story?",
        promptZh: "哪张还是这个故事？",
        correct: { book: "teddy", file: "topic" },
        foils: [
          { book: "swing", file: "topic", bridgeZh: "秋千也来了。小熊想荡秋千吗？小熊在哪儿呢？" },
          { book: "noodles", file: "topic", bridgeZh: "面条也香。小熊吃完面再睡觉？小熊在哪儿呢？" },
          { book: "duck", file: "topic", bridgeZh: "小鸭子也来睡觉了吗？小熊在哪儿呢？" },
        ],
      },
    ],
  },
  {
    id: "bus",
    titleEn: "The Yellow Bus",
    titleZh: "黄色小巴士",
    topicEn: "the yellow bus",
    topicZh: "小巴士",
    parentStayEn: "Catch what he said, then ask back to the yellow bus.",
    parentStayZh: "先接住他的话，再问回小巴士。他说恐龙：恐龙呀。那恐龙也要坐黄色小巴士吗？黄色小巴士呢？",
    parentCarZh: "车也来了。那小车要跟黄色小巴士一起开吗？黄色小巴士呢？",
    belongFoil: {
      book: "grandma",
      file: "p1",
      bridgeZh: "奶奶也来坐小巴士了吗？黄色小巴士呢？",
    },
    pages: [
      {
        id: "p1",
        en: "Tao hears a rumble. The yellow bus comes down the quiet street. “My bus!” He waves. The bus slows.",
        zh: "轰隆轰隆，什么来了？黄色小巴士！小涛在挥手呢。",
      },
      {
        id: "p2",
        en: "The door opens. Step, step. Tao gets on the yellow bus. It smells a little like seats and morning. “I’m in.”",
        zh: "门开了。小涛踩上去。上来啦！",
      },
      {
        id: "p3",
        en: "Tao sits by the window. Trees slide by. He taps the glass. “Hello, trees.” The yellow bus hums.",
        zh: "坐在窗边。树从旁边过去。坐巴士好不好玩？",
      },
      {
        id: "p4",
        en: "The yellow bus stops. The door opens again. Friends wait. “Hello!” says Tao. He is glad the bus brought him.",
        zh: "到了到了！门打开，朋友在等他。下车打招呼喽。",
      },
    ],
    seq: ["p1", "p2", "p4"],
    belongOn: ["p1", "p2", "p4"],
    questions: [
      {
        skill: "detail",
        promptEn: "Tao hears a rumble. What comes down the street?",
        promptZh: "街上开来的是什么？黄色的那个。",
        correct: { book: "bus", file: "p1" },
        foils: [
          { book: "bus", file: "p2", bridgeZh: "这张也是小巴士。已经上车了。那街上刚开来、他还在挥手，是哪一张？" },
          { book: "bus", file: "p3", bridgeZh: "这张也是小巴士。已经坐窗边了。那街上刚开来，是哪一张？" },
          { book: "bus", file: "p4", bridgeZh: "这张也是小巴士。已经到了。那街上刚开来，是哪一张？" },
        ],
      },
      {
        skill: "sequence",
        promptEn: "The yellow bus came first. What happened first?",
        promptZh: "小巴士刚开过来、小涛还在挥手，是哪一张？",
        correct: { book: "bus", file: "p1" },
        foils: [
          { book: "bus", file: "p2", bridgeZh: "这张也是小巴士。已经踩上去了。那刚开过来、还在挥手，是哪一张？" },
          { book: "bus", file: "p3", bridgeZh: "这张也是小巴士。已经坐窗边了。那刚开过来、还在挥手，是哪一张？" },
          { book: "bus", file: "p4", bridgeZh: "这张也是小巴士。已经到了。那刚开过来、还在挥手，是哪一张？" },
        ],
      },
      {
        skill: "topic",
        joinPractice: true,
        promptEn: "Which picture is still our bus story?",
        promptZh: "哪张还是这个故事？",
        correct: { book: "bus", file: "topic" },
        foils: [
          { book: "hat", file: "topic", bridgeZh: "帽子也来了。戴着帽子坐小巴士吗？黄色小巴士呢？" },
          { book: "noodles", file: "topic", bridgeZh: "面条也香。坐小巴士去吃面吗？黄色小巴士呢？" },
          { book: "duck", file: "topic", bridgeZh: "小鸭子也来坐小巴士了吗？黄色小巴士呢？" },
        ],
      },
    ],
  },
  {
    id: "noodles",
    titleEn: "Noodle Day",
    titleZh: "吃面条",
    topicEn: "noodles",
    topicZh: "面条",
    parentStayEn: "Catch what he said, then ask back to the noodles.",
    parentStayZh: "先接住他的话，再问回面条。他说恐龙：恐龙呀。那恐龙想吃什么面？碗在哪儿？",
    parentCarZh: "车也来了。那小车也来吃面了吗？碗在哪儿？面吃完了没？",
    belongFoil: {
      book: "duck",
      file: "p1",
      bridgeZh: "小鸭子也来吃面了吗？碗在哪儿？面吃完了没？",
    },
    pages: [
      {
        id: "p1",
        en: "Yuan stands by the stove. The pot is hot. Little bubbles. Steam kisses his face. “Noodles soon,” he says.",
        zh: "厨房里香香的。小元踩着凳子看锅。面快好了吧？",
      },
      {
        id: "p2",
        en: "Long noodles slip into the pot. Plop. The water dances. It smells like warm kitchen. Yuan watches, hungry.",
        zh: "揭开盖子——哇！面条出来了。好长一缕，看见没？",
      },
      {
        id: "p3",
        en: "Slurp! Yuan eats noodles. Hot. Soft. Yum. “Careful,” he whispers, because steam is still coming up.",
        zh: "嘶溜——吃面啦！热热的，小心烫哦。好吃吗？",
      },
      {
        id: "p4",
        en: "The bowl is empty. A little soup left. Yuan pats his tummy. “All done. Thank you, noodles.”",
        zh: "吃完啦！碗里只剩一点点汤。肚子圆圆的，饱了吧？",
      },
    ],
    seq: ["p1", "p3", "p4"],
    belongOn: ["p2", "p3", "p4"],
    questions: [
      {
        skill: "detail",
        promptEn: "The kitchen smells warm. What does Yuan eat?",
        promptZh: "小元嘶溜嘶溜吃的是什么？",
        correct: { book: "noodles", file: "p3" },
        foils: [
          { book: "noodles", file: "p1", bridgeZh: "这张也是面条。还在看锅。那嘶溜嘶溜吃面，是哪一张？" },
          { book: "noodles", file: "p2", bridgeZh: "这张也是面条。刚出锅。那嘶溜嘶溜吃面，是哪一张？" },
          { book: "noodles", file: "p4", bridgeZh: "这张也是面条。已经吃完了。那嘶溜嘶溜吃面，是哪一张？" },
        ],
      },
      {
        skill: "sequence",
        promptEn: "Yuan pats his tummy. What happened last?",
        promptZh: "吃完了、碗空了，是哪一张？",
        correct: { book: "noodles", file: "p4" },
        foils: [
          { book: "noodles", file: "p1", bridgeZh: "这张也是面条。面还没好。那吃完了、碗空了，是哪一张？" },
          { book: "noodles", file: "p2", bridgeZh: "这张也是面条。刚出锅。那吃完了、碗空了，是哪一张？" },
          { book: "noodles", file: "p3", bridgeZh: "这张也是面条。正在吃。那吃完了、碗空了，是哪一张？" },
        ],
      },
      {
        skill: "topic",
        joinPractice: true,
        promptEn: "Which picture is still our noodle story?",
        promptZh: "哪张还是这个故事？",
        correct: { book: "noodles", file: "topic" },
        foils: [
          { book: "swing", file: "topic", bridgeZh: "秋千也来了。吃完面再荡秋千？碗在哪儿？" },
          { book: "teddy", file: "topic", bridgeZh: "小熊也来吃面了吗？碗在哪儿？面吃完了没？" },
          { book: "grandma", file: "topic", bridgeZh: "奶奶也来了。奶奶煮的面吗？碗在哪儿？" },
        ],
      },
    ],
  },
  {
    id: "grandma",
    titleEn: "Grandma's Hug",
    titleZh: "奶奶的拥抱",
    topicEn: "Grandma",
    topicZh: "奶奶",
    parentStayEn: "Catch what he said, then ask back to Grandma.",
    parentStayZh: "先接住他的话，再问回奶奶。他说恐龙：恐龙呀。那恐龙也来找奶奶了吗？奶奶在哪儿呀？",
    parentCarZh: "车也来了。那小车也来奶奶家了吗？奶奶在哪儿呀？",
    belongFoil: {
      book: "duck",
      file: "p1",
      bridgeZh: "小鸭子也来找奶奶了吗？奶奶在哪儿呀？",
    },
    pages: [
      {
        id: "p1",
        en: "Lin walks to Grandma’s house. Flowers by the door. Her heart goes a little fast. “Grandma is inside.”",
        zh: "走喽，去奶奶家。你看，奶奶在门口！她在等谁呀？",
      },
      {
        id: "p2",
        en: "The door opens. Grandma’s glasses shine. “Hello, my girl!” Lin smells soap and kitchen. She smiles big.",
        zh: "门开了。奶奶招手：来啦来啦。小林好高兴。",
      },
      {
        id: "p3",
        en: "Grandma tells a story. Soft voice. Lin leans in, because she wants every word. The lamp is warm.",
        zh: "进屋了。奶奶讲故事，小林坐旁边听。好听吗？",
      },
      {
        id: "p4",
        en: "Grandma’s arms wrap around Lin. The hug is slow and tight. Lin feels safe. “I love you, Grandma.”",
        zh: "抱抱！奶奶把小林抱紧。安心了吧？",
      },
    ],
    seq: ["p1", "p2", "p4"],
    belongOn: ["p2", "p3", "p4"],
    questions: [
      {
        skill: "detail",
        promptEn: "Lin smells soap and kitchen. Who opens the door and says hello?",
        promptZh: "谁在门口招手呀？",
        correct: { book: "grandma", file: "p2" },
        foils: [
          { book: "grandma", file: "p1", bridgeZh: "这张也是奶奶。还在门口等。那招手说来啦来啦，是哪一张？" },
          { book: "grandma", file: "p3", bridgeZh: "这张也是奶奶。已经在讲故事了。那门口招手，是哪一张？" },
          { book: "grandma", file: "p4", bridgeZh: "这张也是奶奶。已经抱抱了。那门口招手，是哪一张？" },
        ],
      },
      {
        skill: "inference",
        promptEn: "The hug is slow and tight. How does Lin feel?",
        promptZh: "奶奶抱紧她了，是哪一张？",
        correct: { book: "grandma", file: "p4" },
        foils: [
          { book: "grandma", file: "p1", bridgeZh: "这张也是奶奶。还在门口。那抱紧她了，是哪一张？" },
          { book: "grandma", file: "p2", bridgeZh: "这张也是奶奶。刚招手。那抱紧她了，是哪一张？" },
          { book: "grandma", file: "p3", bridgeZh: "这张也是奶奶。在讲故事。那抱紧她了，是哪一张？" },
        ],
      },
      {
        skill: "topic",
        joinPractice: true,
        promptEn: "Which picture is still our Grandma story?",
        promptZh: "哪张还是这个故事？",
        correct: { book: "grandma", file: "topic" },
        foils: [
          { book: "duck", file: "topic", bridgeZh: "小鸭子也来找奶奶了吗？奶奶在哪儿呀？" },
          { book: "noodles", file: "topic", bridgeZh: "面条也香。奶奶煮面了吗？奶奶在哪儿呀？" },
          { book: "teddy", file: "topic", bridgeZh: "小熊也来找奶奶了吗？奶奶在哪儿呀？" },
        ],
      },
    ],
  },
  {
    id: "help",
    titleEn: "I Can Help",
    titleZh: "我来帮忙",
    topicEn: "helping",
    topicZh: "帮忙",
    parentStayEn: "Catch what he said, then ask back to helping.",
    parentStayZh: "先接住他的话，再问回帮忙。他说恐龙：恐龙呀。那恐龙也来帮忙拿袋子吗？谁在拿袋子呀？",
    parentCarZh: "车也来了。那小车要帮妈妈拿袋子吗？谁在拿袋子呀？",
    belongFoil: {
      book: "teddy",
      file: "p2",
      bridgeZh: "小熊也来帮忙了吗？谁在拿袋子呀？",
    },
    pages: [
      {
        id: "p1",
        en: "Mom’s bags are heavy. Her arms look tired. Ping watches. “Too heavy,” he thinks. He wants to help.",
        zh: "妈妈袋子好重哦。小平看着，有点担心。要帮忙吗？",
      },
      {
        id: "p2",
        en: "Ping takes one bag. It bumps his knees. He holds on, because Mom still has the other. “I can help.”",
        zh: "小平也拿一个袋子。有点重，可他还是拿着。帮上忙了吧？",
      },
      {
        id: "p3",
        en: "They walk home together. Step, step. The bags rustle. Ping feels proud, even when his hands get warm.",
        zh: "一起走回家。妈妈一个袋子，小平一个。他笑了，你看见没？",
      },
      {
        id: "p4",
        en: "Bags down. Mom kneels. “Thank you, Ping.” Her voice is soft. Ping’s chest feels big and happy.",
        zh: "到家了。妈妈蹲下来谢谢他。帮忙的感觉好不好？",
      },
    ],
    seq: ["p1", "p2", "p4"],
    belongOn: ["p1", "p2", "p4"],
    questions: [
      {
        skill: "detail",
        promptEn: "The bag bumps Ping’s knees. What does he carry?",
        promptZh: "小平手里拿的是什么？",
        correct: { book: "help", file: "p2" },
        foils: [
          { book: "help", file: "p1", bridgeZh: "这张也是帮忙。还在看。那手里已经拿着袋子，是哪一张？" },
          { book: "help", file: "p3", bridgeZh: "这张也是帮忙。已经一起走了。那刚拿起袋子，是哪一张？" },
          { book: "help", file: "p4", bridgeZh: "这张也是帮忙。已经到家了。那手里拿着袋子，是哪一张？" },
        ],
      },
      {
        skill: "inference",
        promptEn: "Mom says thank you in a soft voice. How does she feel?",
        promptZh: "妈妈蹲下来谢谢他，是哪一张？",
        correct: { book: "help", file: "p4" },
        foils: [
          { book: "help", file: "p1", bridgeZh: "这张也是帮忙。袋子还很重。那妈妈蹲下来谢谢他，是哪一张？" },
          { book: "help", file: "p2", bridgeZh: "这张也是帮忙。刚拿起袋子。那妈妈蹲下来谢谢他，是哪一张？" },
          { book: "help", file: "p3", bridgeZh: "这张也是帮忙。还在走路。那到家、妈妈谢谢他，是哪一张？" },
        ],
      },
      {
        skill: "topic",
        joinPractice: true,
        promptEn: "Which picture is still our helping story?",
        promptZh: "哪张还是这个故事？",
        correct: { book: "help", file: "topic" },
        foils: [
          { book: "rain", file: "topic", bridgeZh: "下雨了。袋子淋湿了吗？谁在拿袋子呀？" },
          { book: "duck", file: "topic", bridgeZh: "小鸭子也来帮忙了吗？谁在拿袋子呀？" },
          { book: "noodles", file: "topic", bridgeZh: "面条也香。袋子里有面吗？谁在拿袋子呀？" },
        ],
      },
    ],
  },
];
