/* Original Story Time books. Short plots (one character, one problem, one ending).
   Topic maintenance is the skill: stay with THIS story. Not copyrighted test items. */
const STORY_BOOKS = [
  {
    id: "hat",
    titleEn: "The Yellow Hat",
    titleZh: "小黄帽",
    topicEn: "the yellow hat",
    topicZh: "小黄帽",
    parentStayEn: "Wait. This story is about the yellow hat. First… then…",
    parentStayZh: "等一等。这个故事说的是小黄帽。先……然后……",
    parentCarEn: "Cars after this book. Right now: where is the hat?",
    parentCarZh: "车等到这本书讲完。现在：帽子在哪里？",
    pages: [
      { id: "p1", en: "Min wears a yellow hat.", zh: "小明戴着小黄帽。" },
      { id: "p2", en: "The wind blows. The hat flies.", zh: "风吹来。帽子飞走了。" },
      { id: "p3", en: "Min looks for the hat.", zh: "小明找帽子。" },
      { id: "p4", en: "Min finds the hat. Hooray!", zh: "小明找到帽子了。好呀！" },
    ],
    seq: ["p1", "p2", "p4"],
    belongOn: ["p1", "p2", "p4"],
    questions: [
      {
        skill: "detail",
        promptEn: "Who wears the yellow hat?",
        promptZh: "谁戴着小黄帽？",
        correct: { book: "hat", file: "p1" },
        foils: [
          { book: "duck", file: "p1" },
          { book: "grandma", file: "topic" },
          { kind: "car" },
        ],
      },
      {
        skill: "sequence",
        promptEn: "What happened first?",
        promptZh: "先发生了什么？",
        correct: { book: "hat", file: "p1" },
        foils: [
          { book: "hat", file: "p2" },
          { book: "hat", file: "p4" },
          { kind: "car" },
        ],
      },
      {
        skill: "topic",
        promptEn: "Which picture is still our hat story?",
        promptZh: "哪一张还是帽子的故事？",
        correct: { book: "hat", file: "topic" },
        foils: [{ kind: "car" }, { book: "bus", file: "topic" }, { book: "noodles", file: "topic" }],
      },
    ],
  },
  {
    id: "rain",
    titleEn: "Rain Rain",
    titleZh: "下雨了",
    topicEn: "the rain",
    topicZh: "下雨",
    parentStayEn: "Wait. This story is about the rain. First… then…",
    parentStayZh: "等一等。这个故事说的是下雨。先……然后……",
    parentCarEn: "Cars after this book. Right now: where is the umbrella?",
    parentCarZh: "车等到这本书讲完。现在：伞在哪里？",
    pages: [
      { id: "p1", en: "The sky is gray.", zh: "天灰灰的。" },
      { id: "p2", en: "Rain, rain, rain.", zh: "下雨了，下雨了。" },
      { id: "p3", en: "We open the umbrella.", zh: "我们打开伞。" },
      { id: "p4", en: "We jump in a puddle. Splash!", zh: "我们跳水坑。哗啦！" },
    ],
    seq: ["p1", "p2", "p4"],
    belongOn: ["p2", "p3", "p4"],
    questions: [
      {
        skill: "detail",
        promptEn: "What do we open in the rain?",
        promptZh: "下雨时我们打开什么？",
        correct: { book: "rain", file: "p3" },
        foils: [{ book: "hat", file: "topic" }, { book: "ball", file: "topic" }, { kind: "car" }],
      },
      {
        skill: "sequence",
        promptEn: "What happened last?",
        promptZh: "最后发生了什么？",
        correct: { book: "rain", file: "p4" },
        foils: [
          { book: "rain", file: "p1" },
          { book: "rain", file: "p3" },
          { kind: "car" },
        ],
      },
      {
        skill: "topic",
        promptEn: "Which picture is still our rain story?",
        promptZh: "哪一张还是下雨的故事？",
        correct: { book: "rain", file: "topic" },
        foils: [{ kind: "car" }, { book: "teddy", file: "topic" }, { book: "bus", file: "topic" }],
      },
    ],
  },
  {
    id: "duck",
    titleEn: "Little Duck Helps",
    titleZh: "小鸭子帮忙",
    topicEn: "the little duck",
    topicZh: "小鸭子",
    parentStayEn: "Wait. This story is about the little duck. First… then…",
    parentStayZh: "等一等。这个故事说的是小鸭子。先……然后……",
    parentCarEn: "Cars after this book. Right now: what is the duck doing?",
    parentCarZh: "车等到这本书讲完。现在：小鸭子在做什么？",
    pages: [
      { id: "p1", en: "Little Duck sees a stick.", zh: "小鸭子看见一根树枝。" },
      { id: "p2", en: "The nest is broken.", zh: "鸟窝坏了。" },
      { id: "p3", en: "Duck brings the stick.", zh: "鸭子衔来树枝。" },
      { id: "p4", en: "The nest is safe. Thank you!", zh: "鸟窝好了。谢谢！" },
    ],
    seq: ["p1", "p3", "p4"],
    belongOn: ["p1", "p3", "p4"],
    questions: [
      {
        skill: "detail",
        promptEn: "Who helps with the stick?",
        promptZh: "谁衔来树枝帮忙？",
        correct: { book: "duck", file: "p3" },
        foils: [{ book: "hat", file: "p1" }, { book: "help", file: "p2" }, { kind: "car" }],
      },
      {
        skill: "sequence",
        promptEn: "What happened last?",
        promptZh: "最后发生了什么？",
        correct: { book: "duck", file: "p4" },
        foils: [
          { book: "duck", file: "p1" },
          { book: "duck", file: "p2" },
          { kind: "car" },
        ],
      },
      {
        skill: "topic",
        promptEn: "Which picture is still our duck story?",
        promptZh: "哪一张还是小鸭子的故事？",
        correct: { book: "duck", file: "topic" },
        foils: [{ kind: "car" }, { book: "swing", file: "topic" }, { book: "noodles", file: "topic" }],
      },
    ],
  },
  {
    id: "swing",
    titleEn: "The Red Swing",
    titleZh: "红色秋千",
    topicEn: "the red swing",
    topicZh: "红色秋千",
    parentStayEn: "Wait. This story is about the red swing. First… then…",
    parentStayZh: "等一等。这个故事说的是红色秋千。先……然后……",
    parentCarEn: "Cars after this book. Right now: who is on the swing?",
    parentCarZh: "车等到这本书讲完。现在：谁在秋千上？",
    pages: [
      { id: "p1", en: "The park has a red swing.", zh: "公园里有红色秋千。" },
      { id: "p2", en: "I sit on the swing.", zh: "我坐上秋千。" },
      { id: "p3", en: "I swing high.", zh: "我荡得高高的。" },
      { id: "p4", en: "I get down. All done.", zh: "我下来了。好了。" },
    ],
    seq: ["p1", "p2", "p4"],
    belongOn: ["p2", "p3", "p4"],
    questions: [
      {
        skill: "detail",
        promptEn: "Where is the swing?",
        promptZh: "秋千在哪里？",
        correct: { book: "swing", file: "p1" },
        foils: [{ book: "teddy", file: "p3" }, { book: "noodles", file: "p3" }, { kind: "car" }],
      },
      {
        skill: "sequence",
        promptEn: "What happened first?",
        promptZh: "先发生了什么？",
        correct: { book: "swing", file: "p1" },
        foils: [
          { book: "swing", file: "p3" },
          { book: "swing", file: "p4" },
          { kind: "car" },
        ],
      },
      {
        skill: "topic",
        promptEn: "Which picture is still our swing story?",
        promptZh: "哪一张还是秋千的故事？",
        correct: { book: "swing", file: "topic" },
        foils: [{ kind: "car" }, { book: "hat", file: "topic" }, { book: "bus", file: "topic" }],
      },
    ],
  },
  {
    id: "ball",
    titleEn: "The Red Ball",
    titleZh: "红皮球",
    topicEn: "the red ball",
    topicZh: "红皮球",
    parentStayEn: "Wait. This story is about the red ball. First… then…",
    parentStayZh: "等一等。这个故事说的是红皮球。先……然后……",
    parentCarEn: "Cars after this book. Right now: who is playing with the ball?",
    parentCarZh: "车等到这本书讲完。现在：谁在玩球？",
    pages: [
      { id: "p1", en: "I have a red ball.", zh: "我有一个红皮球。" },
      { id: "p2", en: "A friend comes.", zh: "一个朋友来了。" },
      { id: "p3", en: "We share the ball.", zh: "我们一起玩球。" },
      { id: "p4", en: "We smile. We are friends.", zh: "我们笑。我们是朋友。" },
    ],
    seq: ["p1", "p2", "p4"],
    belongOn: ["p1", "p3", "p4"],
    questions: [
      {
        skill: "detail",
        promptEn: "What do the friends share?",
        promptZh: "朋友们一起玩什么？",
        correct: { book: "ball", file: "p3" },
        foils: [{ book: "teddy", file: "topic" }, { book: "noodles", file: "topic" }, { kind: "car" }],
      },
      {
        skill: "inference",
        promptEn: "How do they feel at the end?",
        promptZh: "最后他们心里怎么样？",
        correct: { book: "ball", file: "p4" },
        foils: [
          { book: "ball", file: "p1" },
          { book: "hat", file: "p2" },
          { kind: "car" },
        ],
      },
      {
        skill: "topic",
        promptEn: "Which picture is still our ball story?",
        promptZh: "哪一张还是皮球的故事？",
        correct: { book: "ball", file: "topic" },
        foils: [{ kind: "car" }, { book: "duck", file: "topic" }, { book: "help", file: "topic" }],
      },
    ],
  },
  {
    id: "teddy",
    titleEn: "Night Night Teddy",
    titleZh: "晚安小熊",
    topicEn: "teddy",
    topicZh: "小熊",
    parentStayEn: "Wait. This story is about teddy. First… then…",
    parentStayZh: "等一等。这个故事说的是小熊。先……然后……",
    parentCarEn: "Cars after this book. Right now: where is teddy?",
    parentCarZh: "车等到这本书讲完。现在：小熊在哪里？",
    pages: [
      { id: "p1", en: "The moon is out.", zh: "月亮出来了。" },
      { id: "p2", en: "I hug teddy.", zh: "我抱抱小熊。" },
      { id: "p3", en: "We get in bed.", zh: "我们上床。" },
      { id: "p4", en: "Eyes closed. Night-night.", zh: "闭上眼睛。晚安。" },
    ],
    seq: ["p1", "p2", "p4"],
    belongOn: ["p2", "p3", "p4"],
    questions: [
      {
        skill: "detail",
        promptEn: "Who do we hug at bedtime?",
        promptZh: "睡觉前我们抱谁？",
        correct: { book: "teddy", file: "p2" },
        foils: [{ book: "duck", file: "topic" }, { book: "grandma", file: "topic" }, { kind: "car" }],
      },
      {
        skill: "sequence",
        promptEn: "What happened last?",
        promptZh: "最后发生了什么？",
        correct: { book: "teddy", file: "p4" },
        foils: [
          { book: "teddy", file: "p1" },
          { book: "teddy", file: "p2" },
          { kind: "car" },
        ],
      },
      {
        skill: "topic",
        promptEn: "Which picture is still our teddy story?",
        promptZh: "哪一张还是小熊的故事？",
        correct: { book: "teddy", file: "topic" },
        foils: [{ kind: "car" }, { book: "swing", file: "topic" }, { book: "bus", file: "topic" }],
      },
    ],
  },
  {
    id: "bus",
    titleEn: "The Yellow Bus",
    titleZh: "黄色小巴士",
    topicEn: "the yellow bus",
    topicZh: "小巴士",
    parentStayEn: "Wait. This story is about the yellow bus. First… then…",
    parentStayZh: "等一等。这个故事说的是黄色小巴士。先……然后……",
    parentCarEn: "Other cars after this book. Right now: where is the yellow bus?",
    parentCarZh: "别的车等到这本书讲完。现在：小巴士在哪里？",
    pages: [
      { id: "p1", en: "The yellow bus comes.", zh: "黄色小巴士来了。" },
      { id: "p2", en: "I get on the bus.", zh: "我上巴士。" },
      { id: "p3", en: "I sit by the window.", zh: "我坐在窗边。" },
      { id: "p4", en: "The bus stops. Hello!", zh: "巴士停了。你好！" },
    ],
    seq: ["p1", "p2", "p4"],
    belongOn: ["p1", "p2", "p4"],
    questions: [
      {
        skill: "detail",
        promptEn: "What comes down the street?",
        promptZh: "街上开来什么？",
        correct: { book: "bus", file: "p1" },
        foils: [{ kind: "car" }, { book: "duck", file: "p1" }, { book: "help", file: "p1" }],
      },
      {
        skill: "sequence",
        promptEn: "What happened first?",
        promptZh: "先发生了什么？",
        correct: { book: "bus", file: "p1" },
        foils: [
          { book: "bus", file: "p3" },
          { book: "bus", file: "p4" },
          { kind: "car" },
        ],
      },
      {
        skill: "topic",
        promptEn: "Which picture is still our bus story?",
        promptZh: "哪一张还是小巴士的故事？",
        correct: { book: "bus", file: "topic" },
        foils: [{ kind: "car" }, { book: "hat", file: "topic" }, { book: "noodles", file: "topic" }],
      },
    ],
  },
  {
    id: "noodles",
    titleEn: "Noodle Day",
    titleZh: "吃面条",
    topicEn: "noodles",
    topicZh: "面条",
    parentStayEn: "Wait. This story is about noodles. First… then…",
    parentStayZh: "等一等。这个故事说的是面条。先……然后……",
    parentCarEn: "Cars after this book. Right now: where is the bowl?",
    parentCarZh: "车等到这本书讲完。现在：碗在哪里？",
    pages: [
      { id: "p1", en: "The pot is hot.", zh: "锅是热的。" },
      { id: "p2", en: "Noodles go in.", zh: "面条下锅。" },
      { id: "p3", en: "We slurp noodles. Yum.", zh: "我们吃面。好吃。" },
      { id: "p4", en: "The bowl is empty. All done.", zh: "碗空了。吃完了。" },
    ],
    seq: ["p1", "p3", "p4"],
    belongOn: ["p2", "p3", "p4"],
    questions: [
      {
        skill: "detail",
        promptEn: "What do we eat?",
        promptZh: "我们吃什么？",
        correct: { book: "noodles", file: "p3" },
        foils: [{ book: "ball", file: "topic" }, { book: "hat", file: "topic" }, { kind: "car" }],
      },
      {
        skill: "sequence",
        promptEn: "What happened last?",
        promptZh: "最后发生了什么？",
        correct: { book: "noodles", file: "p4" },
        foils: [
          { book: "noodles", file: "p1" },
          { book: "noodles", file: "p2" },
          { kind: "car" },
        ],
      },
      {
        skill: "topic",
        promptEn: "Which picture is still our noodle story?",
        promptZh: "哪一张还是面条的故事？",
        correct: { book: "noodles", file: "topic" },
        foils: [{ kind: "car" }, { book: "swing", file: "topic" }, { book: "bus", file: "topic" }],
      },
    ],
  },
  {
    id: "grandma",
    titleEn: "Grandma's Hug",
    titleZh: "奶奶的拥抱",
    topicEn: "Grandma",
    topicZh: "奶奶",
    parentStayEn: "Wait. This story is about Grandma. First… then…",
    parentStayZh: "等一等。这个故事说的是奶奶。先……然后……",
    parentCarEn: "Cars after this book. Right now: where is Grandma?",
    parentCarZh: "车等到这本书讲完。现在：奶奶在哪里？",
    pages: [
      { id: "p1", en: "We go to Grandma.", zh: "我们去奶奶家。" },
      { id: "p2", en: "Grandma says hello.", zh: "奶奶说你好。" },
      { id: "p3", en: "Grandma tells a story.", zh: "奶奶讲故事。" },
      { id: "p4", en: "Grandma gives a hug.", zh: "奶奶抱抱。" },
    ],
    seq: ["p1", "p2", "p4"],
    belongOn: ["p2", "p3", "p4"],
    questions: [
      {
        skill: "detail",
        promptEn: "Who opens the door?",
        promptZh: "谁开门说你好？",
        correct: { book: "grandma", file: "p2" },
        foils: [{ book: "hat", file: "p1" }, { book: "help", file: "p4" }, { kind: "car" }],
      },
      {
        skill: "inference",
        promptEn: "How does the child feel in the hug?",
        promptZh: "被抱着的时候，小朋友心里怎么样？",
        correct: { book: "grandma", file: "p4" },
        foils: [
          { book: "hat", file: "p2" },
          { book: "rain", file: "p1" },
          { kind: "car" },
        ],
      },
      {
        skill: "topic",
        promptEn: "Which picture is still our Grandma story?",
        promptZh: "哪一张还是奶奶的故事？",
        correct: { book: "grandma", file: "topic" },
        foils: [{ kind: "car" }, { book: "duck", file: "topic" }, { book: "bus", file: "topic" }],
      },
    ],
  },
  {
    id: "help",
    titleEn: "I Can Help",
    titleZh: "我来帮忙",
    topicEn: "helping",
    topicZh: "帮忙",
    parentStayEn: "Wait. This story is about helping. First… then…",
    parentStayZh: "等一等。这个故事说的是帮忙。先……然后……",
    parentCarEn: "Cars after this book. Right now: who is carrying a bag?",
    parentCarZh: "车等到这本书讲完。现在：谁在拿袋子？",
    pages: [
      { id: "p1", en: "The bag is heavy.", zh: "袋子好重。" },
      { id: "p2", en: "I take one bag.", zh: "我拿一个袋子。" },
      { id: "p3", en: "We walk home.", zh: "我们走回家。" },
      { id: "p4", en: "Mom says thank you.", zh: "妈妈说谢谢。" },
    ],
    seq: ["p1", "p2", "p4"],
    belongOn: ["p1", "p2", "p4"],
    questions: [
      {
        skill: "detail",
        promptEn: "What does the child carry?",
        promptZh: "小朋友拿什么？",
        correct: { book: "help", file: "p2" },
        foils: [{ book: "ball", file: "topic" }, { book: "teddy", file: "topic" }, { kind: "car" }],
      },
      {
        skill: "inference",
        promptEn: "How does Mom feel at the end?",
        promptZh: "最后妈妈心里怎么样？",
        correct: { book: "help", file: "p4" },
        foils: [
          { book: "help", file: "p1" },
          { book: "hat", file: "p2" },
          { kind: "car" },
        ],
      },
      {
        skill: "topic",
        promptEn: "Which picture is still our helping story?",
        promptZh: "哪一张还是帮忙的故事？",
        correct: { book: "help", file: "topic" },
        foils: [{ kind: "car" }, { book: "rain", file: "topic" }, { book: "bus", file: "topic" }],
      },
    ],
  },
];
